### ISSUE TITLE
实验的时候发现几个问题

### ISSUE THREAD

**Issue by celetium** [alipay/sofa-kubernetes-demo#2]
我是OSX环境。
1、vmWare Fusion一用Mac就死机；
2、VirtualBox第一次失败说我装的版本太低（明明是最新的），删掉重来就OK；
3、第10步test不成功，需要删掉或pom注掉才行；
4、第13步rpccclient单词多了个c；
5、第16步要尝试多次才成功；
6、第20步zikpin单词写错了应该是zipkin

**Comment by khotyn** [comment]
@celetium 已经更新 Demo，把你提到的几个问题都修复了。
